### ISSUE TITLE
ch05 logRegres.py代码有误

### ISSUE THREAD

**Issue by frisky1985** [shiyipaisizuo/machine_learning_in_action#2]
Hi,
Sorry again, ch05的代码有点问题，具体如下：
1) sigmoid(X)函数有可能会计算溢出，需要增加异常保护
`def sigmoid(X):
    try:
        return 1.0 / (1 + math.exp(-X))
    except OverflowError:
        return 0.  # 返回0.的原因是exp(-X)已经接近无穷大，1/inf -> 0` 
2) stoc_grad_ascent1()函数在del (data_index[rand_index])时出错，原因是data_index = range(m), range()函数返回的是一个元组，不可修改，建议修改如下：
`data_index = list(range(m))`
3) colic_test()和mul_test()函数中的print()调用format()有问题。
`print("...{}".format(...))`
仅供参考。

**Comment by Lornatang** [comment]
Yeah, I understand.

Please provide the number of lines that the function failed.

 - ${line} 
 - ${error_message} 
 - ${amendments}

Thanks

**Comment by frisky1985** [comment]
1. sigmoid(x) function
    $line 29
    $error_message: OverflowError
      The "OverflowError" can be caused because of invoking the math.exp() function with big data.
    $amendment
      `def sigmoid(X):`
      `    try:`
      `        return 1.0 / (1 + math.exp(-X))`
      `    except OverflowError:`
       `       return 0.0 `
2. stoc_grad_ascent1() function
    $line 106
    $error_message: TypeError: 'range' object doesn't support item deletion
    $amendment
    `data_index = list(range(m))`

3. colic_test() function
    $line 160
    $error_message: 
print("the error rate of this test is: {}").format(error_rate)
        ^
SyntaxError: invalid syntax
    $amendment
`print("the error rate of this test is: {}".format(error_rate))`

4. mul_test() function
    $line 173
    $error_message: SyntaxError (listed above in point 3)
    $amendment
`print("after {} iterations the average error rate is: {}".format(num_tests, error_sum / float(num_tests)))`

**Comment by Lornatang** [comment]
The error you pointed out has been corrected. Thanks for your feedback!
