### ISSUE TITLE
随机树中 labels = ['no surfacing', 'flippers'] 是不是少赋值了个 fish？

### ISSUE THREAD

**Issue by hackervv** [shiyipaisizuo/machine_learning_in_action#3]
随机树中 labels = ['no surfacing', 'flippers'] 是不是少赋值了个 fish，特征是三列，遍历labels的时候会不会少一个label，出现问题。

**Comment by hackervv** [comment]
我看书上的决策树图中画出了fish这个label呢！

**Comment by Lornatang** [comment]
Hey, thank you, can you give me a picture? @hackervv

**Comment by hackervv** [comment]
![1570947535(1)](https://user-images.githubusercontent.com/30012205/66711837-2fa28b80-edc6-11e9-8515-cae4fcad6f9d.jpg)

**Comment by Lornatang** [comment]
thank you @hackervv .  I will fix it later.
