### ISSUE TITLE
朴素贝叶斯筛选垃圾邮件中的正则分割单词的公式错误了。

### ISSUE THREAD

**Issue by hackervv** [shiyipaisizuo/machine_learning_in_action#4]
![image](https://user-images.githubusercontent.com/30012205/67190715-08ca0200-f423-11e9-8261-848e176bc150.png)
应该是  re.split('\W+', big_string)！！

**Comment by Lornatang** [comment]
Thank you, I have received, thank you for discovering this error.

**Comment by Lornatang** [comment]
Has been modified, thank you for the error! @hackervv
